@startuml
actor Cripple
entity Bed
entity Server
Cripple -> Bed: Op bed liggen
Bed -> Server: {druksensor:true}
Server -> GUI_Bewaker: {bed_sensor:true}
GUI_Bewaker --> Server: {success:true}
Server --> Bed: {success:true}
alt beweging detectie
    Tafellamp -> Server: {beweging:true}
        Server -> GUI_Bewaker: {inbraak:true}
        activate GUI_Bewaker
                Server <-- GUI_Bewaker: {success:true}
        deactivate GUI_Bewaker
    Server --> Tafellamp: {success:true}
else persoon staat op
        Cripple -> Bed: Van bed af
        Bed -> Server: {druksensor:false}
        Server -> GUI_Bewaker: {bed_sensor:false}

        Server <-- GUI_Bewaker: {success:true}
        Bed <-- Server: {success:true}
end

@enduml
