@startuml
title Muur communicatie sequentie

actor Bewoner
entity Muur
alt omschakeling LDR donker
        Muur -> Muur: setLDRStatus(donker)
else omschakeling LDR licht
        Muur -> Muur: setLDRStatus(licht)
        Muur -> Muur: setLcd(aan)
        Muur -> Server ++: queue(self)
        Muur <-- Server --: {success:true}
end
...
Bewoner -> Muur ++: Draaien aan Potentiometer
Muur -> Server: {potentiometer:<value>}
Server -> Muur: {success:true,led_brightness:<value>}
Muur -> Server: {success:true}
Bewoner <-- Muur --: Klaar
@enduml
